IMG = "files/imagen"
ARPIOS = "files/pickle_harpies"
OBJETOS = 'files/piclke_weapons'
STATUS = 'files/pickle_status'
WEAPONFILE = "files/objetos.txt"
COFFEEFILE = "files/cafes.txt"
REVIVEFILE = "files/revive.txt"
SUICIDEFILE = "files/suicide.txt"
CURSEFILE = "files/curse.txt"
TXT = '.txt'
PNG = '.png'
FONT = "files/font.ttf"
NA = 'NA'
TOKENS = 'tokens'
ACCESS_TOKENS_DIC = {'CONSUMER_KEY': NA, 'CONSUMER_SECRET': NA, 'ACCESS_KEY': NA, 'ACCESS_SECRET': NA}
